### ISSUE TITLE
Logging during test cases

### ISSUE THREAD

**Issue by evanshortiss** [TkeITMobility/tke-cloud-logger#5]
It would be nice to be able to disable logs during test cases. What do people think?

I can think of some methods to do so. One is to check it `NODE_ENV=test` and if so, not print logs. We could do this in the _getDefaultStreams()_ function.

Thoughts?

CC'ing those who have used this so far: @MikeyBurkman @j-burlison @jimdillon @chandu177 @jainmnsh

**Comment by jimdillon** [comment]
@evanshortiss, I like having logs in the tests because of the insight provided especially when writing tests.  However, I do wish they were pretty.

![screen shot 2016-04-05 at 2 13 36 pm](https://cloud.githubusercontent.com/assets/13226422/14293027/b6427594-fb38-11e5-86eb-97fe2056540a.png)

**Comment by MikeyBurkman** [comment]
@jimdillon I think if you piped that to `bunyan` then it would (I think) output them pretty.

I'm rather torn on logging in tests. Logs are primarily for inspection of running production code, but they maybe can be a nice way to debug and trace through some tests. But I'm also not sure how useful the logs can actually be for debugging tests, without them being written primarily for that purpose. (As compared to be written to be read later in production.)

They're also quite noisy when just doing regular development, especially as we get more and more tests. Maybe we disable logging during tests by default, and add a function `log.enableForTests(loggerName)` if we really need them on a case-by-case basis? Would require a bit of changes though.

At the very least, we should really make sure we're not writing to mongo during testing...

**Comment by jimdillon** [comment]
@MikeyBurkman, thanks for the tip! What / how would I pipe that to bunyan?  (Possibly the test script in package.json?)

``` javascript
"scripts": {
    "debug": "grunt serve",
    "jshint": "jshint lib/**/*.js",
    "start": "grunt serve | bunyan",
    "test": "npm run-script jshint; npm run-script coverage && npm run-script check-coverage",
    "coverage": "env NODE_PATH=. NODE_ENV=test istanbul cover -x *.test.js _mocha $(find ./lib -name \"*.test.js\")",
    "check-coverage": "istanbul check-coverage --statements 100 --branches 100 --functions 100 --lines 100",
    "unit": "env NODE_PATH=. NODE_ENV=test _mocha $(find ./lib -name \"*.test.js\")"
  },
```

**Comment by MikeyBurkman** [comment]
You should just be able to do it the normal Unix way: `npm test | bunyan` on the command line. Just need make sure bunyan is on your path line by doing `npm i -g bunyan` first.

**Comment by evanshortiss** [comment]
Hey @jimdillon you'd pipe it the way I showed for the cloud app previously, exact same process. @MikeyBurkman has it covered here too.

Try change the unit script too have this at the end `| bunyan`

**Comment by evanshortiss** [comment]
"Maybe we disable logging during tests by default, and add a function log.enableForTests(loggerName)" I think this is sensible @MikeyBurkman, but definitely requires some work as you've said.

Perhaps we can break it into two pieces of work that allows for easy transition.
1. Add code that checks for NODE_ENV=test (or something else we agree on) in the _getDefaultStreams_ function. If truthy then no streams are added to the logger, thus disabling output. If you want output in a test, just remove/change NODE_ENV.

We can then have a separate task for _log.enableForTests(loggerName)_ since it's a little more complex.

Thoughts?

**Comment by jimdillon** [comment]
@MikeyBurkman @evanshortiss, after running the logger during testing, I have to agree with y'all that the log output is detracting and jumbles things up.  However, I do at times need to log things out in my tests while developing them.

**Comment by MikeyBurkman** [comment]
@jimdillon I guess the question is whether it would be logging that you would leave in, or whether it's just there to trace things through while you're working on it, and then can be deleted. If that, then I say just console.log() away (and make sure to delete them all before submitting a PR).

There are probably better options using a Node debugger though. @evanshortiss Any experience using a node debugger during tests?

**Comment by jimdillon** [comment]
@MikeyBurkman, I can live with that.

**Comment by MikeyBurkman** [comment]
Maybe try this out? I haven't messed with it but seems pretty simple. http://stackoverflow.com/a/14586655

**Comment by jimdillon** [comment]
Thanks Mike!

**Comment by evanshortiss** [comment]
@MikeyBurkman that's the one, the _--debug-brk_ flag. @jimdillon 

I might put a PR in here for the NODE_ENV so if there's no objection.

**Comment by MikeyBurkman** [comment]
Which is obviously short for --debug-burkman

**Comment by MikeyBurkman** [comment]
I started setting `TKE_LOG_SILENT=true` to the command when running unit tests, and this cleaned things up nicely.
